"""M2 EDA: answers the open questions in docs/breakdown.md. Writes tables to docs/eda.md.

Numbers only (no plots). Sources are up to ~5.3M rows each, so:
- Anything vectorizable in pandas/numpy (non-ASCII detection, dupes, postcode regex) is vectorized —
  no `.apply(axis=1)` and no Python-level per-row loops over full DataFrames.
- Anything that must call rapidfuzz/anyascii per pair (there's no vectorized fuzzy-match) is capped
  with a sample: true positives (B6, C7, C9) and per-country token vocab (D11) all sample rather than
  run over the full population — full-population rapidfuzz over millions of pairs doesn't finish in
  EDA-script time regardless of how the loop is written.
"""
import random
import re
import unicodedata
from collections import Counter
from pathlib import Path

import numpy as np
import pandas as pd
from anyascii import anyascii
from rapidfuzz.fuzz import token_set_ratio

from .io import ROOT, load_gt, load_source

SEED = 42
OUT = ROOT / "docs" / "eda.md"
STOPWORDS_MIN_LEN = 2  # tokens shorter than this are noise, not vocabulary
NAME_RE = re.compile(r"[a-z0-9]+")


def norm_tokens(s: str) -> list[str]:
    return [t for t in NAME_RE.findall(anyascii(s).lower()) if len(t) >= STOPWORDS_MIN_LEN]


def exact_norm_name(s: str) -> str:
    return " ".join(NAME_RE.findall(anyascii(s).lower()))


POSTCODE_RE = {"US": re.compile(r"\b\d{5}\b"), "India": re.compile(r"\b\d{6}\b"), "France": re.compile(r"\b\d{5}\b")}


def postcode_of(addr: str, country: str) -> str | None:
    rx = POSTCODE_RE.get(country)
    m = rx.search(addr) if rx else None
    return m.group(0) if m else None


def nonascii_mask(s: pd.Series) -> pd.Series:
    """Vectorized non-ASCII detection: str.encode raises on non-ASCII input, applied C-side per element."""
    return ~s.str.fullmatch(r"[\x00-\x7F]*", na=False)


def unicode_scripts(s: str) -> set[str]:
    scripts = set()
    for ch in s:
        if ord(ch) < 128:
            continue
        try:
            name = unicodedata.name(ch)
        except ValueError:
            continue
        scripts.add(name.split()[0])
    return scripts


def lookup(split: str, n: int) -> dict[str, tuple[str, str, str]]:
    """id -> (business_name, business_address, country)."""
    df = load_source(split, n)
    return dict(zip(df["entity_id"], zip(df["business_name"], df["business_address"], df["country"])))


def md_table(rows: list[dict], f) -> None:
    if not rows:
        f.write("_(no rows)_\n\n")
        return
    cols = list(rows[0].keys())
    f.write("| " + " | ".join(cols) + " |\n")
    f.write("|" + "|".join("---" for _ in cols) + "|\n")
    for r in rows:
        f.write("| " + " | ".join(str(r[c]) for c in cols) + " |\n")
    f.write("\n")


def pct(n: int, d: int) -> str:
    return f"{100 * n / d:.2f}%" if d else "n/a"


def main() -> None:
    rng = random.Random(SEED)
    truth = load_gt()
    s1_train = lookup("train", 1)
    s2_train = lookup("train", 2)
    s3_train = lookup("train", 3)
    train_lookup = {**s2_train, **s3_train}

    f = open(OUT, "w", encoding="utf-8")
    f.write("# EDA (M2)\nGenerated by `src/eda.py`, seed 42. Numbers only; see docs/breakdown.md Revision 2 for conclusions.\n\n")

    # ---------- A. Structure ----------
    f.write("## A. Structure\n\n### A1. Assignment (one S2/S3 id under >1 S1?)\n")
    id_to_s1_count = Counter(i for v in truth.values() for i in v)
    multi = {i: c for i, c in id_to_s1_count.items() if c > 1}
    f.write(f"- Matched ids total (with duplicates across S1): {sum(id_to_s1_count.values())}\n")
    f.write(f"- Distinct matched ids: {len(id_to_s1_count)}\n")
    f.write(f"- Ids appearing under >1 S1 entity: {len(multi)} ({pct(len(multi), len(id_to_s1_count))})\n")
    if multi:
        ex = list(multi.items())[:5]
        f.write(f"- Examples (id: #S1 entities): {ex}\n")
    f.write("\n")

    f.write("### A2. Cardinality per S1 (total, #S2, #S3)\n")
    sizes = np.array([len(v) for v in truth.values()])
    n_s2 = np.array([sum(i.startswith("S2-") for i in v) for v in truth.values()])
    n_s3 = np.array([sum(i.startswith("S3-") for i in v) for v in truth.values()])
    rows = []
    for name, arr in [("total", sizes), ("#S2", n_s2), ("#S3", n_s3)]:
        rows.append({"metric": name, "max": int(arr.max()), "p50": int(np.percentile(arr, 50)),
                     "p90": int(np.percentile(arr, 90)), "p99": int(np.percentile(arr, 99))})
    md_table(rows, f)

    f.write("### A3. Distractors (S2/S3 records matched to no S1), by source x country\n")
    matched_ids = set(id_to_s1_count)
    rows = []
    for n, src_df in [(2, load_source("train", 2, ["entity_id", "country"])),
                       (3, load_source("train", 3, ["entity_id", "country"]))]:
        unmatched = ~src_df["entity_id"].isin(matched_ids)
        totals = src_df["country"].value_counts()
        unmatched_by_country = unmatched.groupby(src_df["country"]).sum()
        for country, total in sorted(totals.items()):
            u = int(unmatched_by_country.get(country, 0))
            rows.append({"source": f"S{n}", "country": country, "records": int(total),
                         "unmatched": u, "distractor_rate": pct(u, total)})
    md_table(rows, f)

    f.write("### A4. Country consistency on true pairs; missing-country rate\n")
    # Build the GT pair table once as a DataFrame (s1_id, match_id) via exploding truth, then join
    # country columns — vectorized, instead of a 7.6M-iteration Python loop over dict items.
    gt_pairs = pd.DataFrame(((s1_id, m) for s1_id, matches in truth.items() for m in matches),
                             columns=["s1_id", "match_id"])
    s1_country_map = {eid: c for eid, (_, _, c) in s1_train.items()}
    match_country_map = {eid: c for eid, (_, _, c) in train_lookup.items()}
    gt_pairs["s1_country"] = gt_pairs["s1_id"].map(s1_country_map)
    gt_pairs["match_country"] = gt_pairs["match_id"].map(match_country_map)
    total_pairs = len(gt_pairs)
    same = gt_pairs["s1_country"] == gt_pairs["match_country"]
    missing = (gt_pairs["s1_country"] == "") | (gt_pairs["match_country"] == "")
    f.write(f"- True pairs: {total_pairs}; country match: {pct(int(same.sum()), total_pairs)}; "
            f"mismatch: {pct(int((~same).sum()), total_pairs)}; missing country either side: {pct(int(missing.sum()), total_pairs)}\n")
    mismatch_ex = (gt_pairs.loc[~same, ["s1_country", "match_country"]]
                   .value_counts().head(10).to_dict())
    f.write(f"- Top country-mismatch pairs (S1_country, match_country): {mismatch_ex}\n\n")

    # ---------- B. Scripts / languages ----------
    f.write("## B. Scripts / languages\n\n### B5. Non-ASCII rate per source x country x field; top scripts\n")
    rows = []
    script_counts: Counter = Counter()
    for split in ("train", "test"):
        for n in (1, 2, 3):
            df = load_source(split, n)
            for field in ("business_name", "business_address"):
                mask = nonascii_mask(df[field])
                counts = mask.groupby(df["country"]).sum()
                totals = df["country"].value_counts()
                for country, total in totals.items():
                    nonascii = int(counts.get(country, 0))
                    rows.append({"split": split, "source": f"S{n}", "country": country, "field": field,
                                 "nonascii_rate": pct(nonascii, total), "n": int(total)})
                    if nonascii:
                        pool = df.loc[mask & (df["country"] == country), field]
                        for v in pool.sample(min(500, len(pool)), random_state=SEED):
                            script_counts.update(unicode_scripts(v))
    md_table(rows, f)
    f.write(f"Top Unicode scripts seen (sampled up to 500 non-ASCII values per group): {script_counts.most_common(10)}\n\n")

    f.write("### B6. True pairs with non-ASCII match: token_set_ratio(anyascii(match name), S1 name) (sampled)\n")
    # Filtering step below is a single any()-per-pair scan over all ~7.6M matched pairs (cheap, no
    # anyascii/rapidfuzz call) — only the expensive similarity computation after it is sampled.
    nonascii_pairs = [(s1_id, m) for s1_id, matches in truth.items() for m in matches
                       if any(ord(c) > 127 for c in train_lookup[m][0])]
    rng.shuffle(nonascii_pairs)
    B6_SAMPLE = 80_000  # rapidfuzz+anyascii per pair; capped, not run over all ~2M+ non-ASCII matches
    sims = []
    examples = []
    for s1_id, m in nonascii_pairs[:B6_SAMPLE]:
        s1_name = s1_train[s1_id][0]
        m_name = train_lookup[m][0]
        translit = anyascii(m_name)
        sim = token_set_ratio(s1_name.lower(), translit.lower())
        sims.append(sim)
        if len(examples) < 15:
            examples.append({"s1_name": s1_name, "raw": m_name, "translit": translit, "sim": round(sim, 1)})
    f.write(f"- non-ASCII true-match pairs found: {len(nonascii_pairs)}; sampled {min(B6_SAMPLE, len(nonascii_pairs))}\n")
    if sims:
        a = np.array(sims)
        f.write(f"- n={len(a)}; p10={np.percentile(a,10):.1f} p50={np.percentile(a,50):.1f} p90={np.percentile(a,90):.1f}\n\n")
    md_table(examples, f)

    # ---------- C. Difficulty ----------
    f.write("## C. Difficulty (sampled)\n\n### C7. token_set_ratio / exact-name / postcode: true pairs vs random same-country non-pairs\n")
    true_pairs = [(s1, m) for s1, ms in truth.items() for m in ms]
    rng.shuffle(true_pairs)
    true_sample = true_pairs[:200_000]

    s1_ids_by_country: dict[str, list[str]] = {}
    for eid, (_, _, c) in s1_train.items():
        s1_ids_by_country.setdefault(c, []).append(eid)
    cand_ids_by_country: dict[str, list[str]] = {}
    for eid, (_, _, c) in train_lookup.items():
        cand_ids_by_country.setdefault(c, []).append(eid)

    neg_sample = []
    s1_id_list = list(s1_train)  # built once — was rebuilt from the 2.2M-entry dict every loop iteration
    while len(neg_sample) < 200_000:
        s1_id = rng.choice(s1_id_list)
        country = s1_train[s1_id][2]
        pool = cand_ids_by_country.get(country)
        if not pool:
            continue
        cand = rng.choice(pool)
        if cand not in truth.get(s1_id, ()):
            neg_sample.append((s1_id, cand))

    def compute(pairs) -> dict[str, np.ndarray]:
        name_sim, addr_sim, exact_name, exact_pc = [], [], [], []
        for s1_id, cid in pairs:
            n1, a1, c1 = s1_train[s1_id]
            n2, a2, c2 = train_lookup[cid]
            name_sim.append(token_set_ratio(anyascii(n1).lower(), anyascii(n2).lower()))
            addr_sim.append(token_set_ratio(anyascii(a1).lower(), anyascii(a2).lower()))
            exact_name.append(exact_norm_name(n1) == exact_norm_name(n2))
            p1, p2 = postcode_of(a1, c1), postcode_of(a2, c2)
            exact_pc.append(bool(p1) and p1 == p2)
        return {"name_sim": np.array(name_sim), "addr_sim": np.array(addr_sim),
                "exact_name": np.array(exact_name), "exact_pc": np.array(exact_pc)}

    pos_stats, neg_stats = compute(true_sample), compute(neg_sample)
    rows = []
    for label, stats, n in [("true pairs", pos_stats, len(true_sample)), ("random non-pairs", neg_stats, len(neg_sample))]:
        rows.append({"class": label, "n": n,
                     "name_sim p10/p50/p90": f"{np.percentile(stats['name_sim'],10):.0f}/{np.percentile(stats['name_sim'],50):.0f}/{np.percentile(stats['name_sim'],90):.0f}",
                     "addr_sim p10/p50/p90": f"{np.percentile(stats['addr_sim'],10):.0f}/{np.percentile(stats['addr_sim'],50):.0f}/{np.percentile(stats['addr_sim'],90):.0f}",
                     "exact_name_rate": pct(int(stats["exact_name"].sum()), n),
                     "exact_postcode_rate": pct(int(stats["exact_pc"].sum()), n)})
    md_table(rows, f)

    f.write("### C8. Postcode presence rate; share of true pairs sharing a postcode\n")
    rows = []
    for split in ("train", "test"):
        for n in (1, 2, 3):
            df = load_source(split, n)
            present = pd.Series(False, index=df.index)
            for country, rx in POSTCODE_RE.items():  # vectorized per-country regex, not per-row apply
                cmask = df["country"] == country
                present[cmask] = df.loc[cmask, "business_address"].str.contains(rx, regex=True)
            for country in df["country"].unique():
                mask = df["country"] == country
                rows.append({"split": split, "source": f"S{n}", "country": country,
                             "postcode_present_rate": pct(int(present[mask].sum()), int(mask.sum()))})
    md_table(rows, f)
    shared = int(pos_stats["exact_pc"].sum())
    f.write(f"- Share of sampled true pairs sharing a postcode: {pct(shared, len(true_sample))}\n\n")

    f.write("### C9. Within-entity similarity: among matched records vs matched-to-S1, for |matches|>=3\n")
    multi_ids = [s1 for s1, ms in truth.items() if len(ms) >= 3]
    rng.shuffle(multi_ids)
    sample_multi = multi_ids[:2000]
    among_sims, to_s1_sims = [], []
    for s1_id in sample_multi:
        matches = list(truth[s1_id])
        names = [anyascii(train_lookup[m][0]).lower() for m in matches]
        s1_name = anyascii(s1_train[s1_id][0]).lower()
        to_s1_sims.extend(token_set_ratio(s1_name, nm) for nm in names)
        for i in range(len(names)):
            for j in range(i + 1, len(names)):
                among_sims.append(token_set_ratio(names[i], names[j]))
    if among_sims and to_s1_sims:
        a, b = np.array(among_sims), np.array(to_s1_sims)
        f.write(f"- Among-matched-records name sim (n={len(a)}): p50={np.percentile(a,50):.1f}\n")
        f.write(f"- Matched-record-to-S1 name sim (n={len(b)}): p50={np.percentile(b,50):.1f}\n")
        f.write(f"- Sampled from {len(sample_multi)} S1 entities with >=3 matches.\n\n")

    f.write("### C10. 30 true pairs with lowest name AND address similarity (rank by min(name_sim, addr_sim))\n")
    combo = sorted(zip(true_sample, pos_stats["name_sim"], pos_stats["addr_sim"]),
                    key=lambda t: min(t[1], t[2]))[:30]
    rows = []
    for (s1_id, cid), nsim, asim in combo:
        n1, a1, _ = s1_train[s1_id]
        n2, a2, _ = train_lookup[cid]
        rows.append({"s1_name": n1, "match_name": n2, "s1_addr": a1, "match_addr": a2,
                     "name_sim": round(nsim, 1), "addr_sim": round(asim, 1)})
    md_table(rows, f)

    # ---------- D. Vocabulary ----------
    D11_SAMPLE = 400_000  # anyascii is pure-Python per call; top-60 tokens stabilize well under full population
    f.write(f"## D. Vocabulary (for normaliser)\n\n### D11. Top 60 tokens per country per source, name & address (sampled up to {D11_SAMPLE:,} rows/group)\n")
    for split in ("train",):
        for n in (1, 2, 3):
            df = load_source(split, n)
            for country in df["country"].unique():
                mask = df["country"] == country
                for field, label in [("business_name", "name"), ("business_address", "addr")]:
                    pool = df.loc[mask, field]
                    pool = pool.sample(min(D11_SAMPLE, len(pool)), random_state=SEED)
                    tokens = Counter()
                    for v in pool:
                        tokens.update(norm_tokens(v))
                    top = tokens.most_common(60)
                    f.write(f"**{split} S{n} {country} {label}** (top 60, n_sampled={len(pool)}): {top}\n\n")

    f.write("### D12. Test France: sample rows, non-ASCII rate, top tokens, postcode presence\n")
    for n in (1, 2, 3):
        df = load_source("test", n)
        fr = df[df["country"] == "France"]
        f.write(f"**test S{n} France** n={len(fr)}\n\n")
        sample_rows = fr.sample(min(15, len(fr)), random_state=SEED)[["entity_id", "business_name", "business_address"]]
        md_table(sample_rows.to_dict("records"), f)
        nonascii_name = sum(any(ord(c) > 127 for c in v) for v in fr["business_name"])
        nonascii_addr = sum(any(ord(c) > 127 for c in v) for v in fr["business_address"])
        f.write(f"- non-ASCII: name {pct(nonascii_name, len(fr))}, address {pct(nonascii_addr, len(fr))}\n")
        present = fr["business_address"].str.contains(POSTCODE_RE["France"], regex=True)
        f.write(f"- postcode (5-digit) present: {pct(int(present.sum()), len(fr))}\n")
        for field, label in [("business_name", "name"), ("business_address", "addr")]:
            tokens = Counter()
            for v in fr[field]:
                tokens.update(norm_tokens(v))
            f.write(f"- top 60 {label} tokens: {tokens.most_common(60)}\n\n")

    # ---------- E. Skill-required checks (structural nulls/dupes, channel split, blocking scale, hardness gap) ----------
    f.write("## E. Skill checks (eda-fe-entity-resolution-hackathon)\n\n### E1. Null/empty name or address; exact duplicate name+address within a source\n")
    rows = []
    for split in ("train", "test"):
        for n in (1, 2, 3):
            df = load_source(split, n)
            empty_name = int((df["business_name"].str.strip() == "").sum())
            empty_addr = int((df["business_address"].str.strip() == "").sum())
            dup = int(df.duplicated(subset=["business_name", "business_address"]).sum())
            rows.append({"split": split, "source": f"S{n}", "n": len(df), "empty_name": empty_name,
                         "empty_addr": empty_addr, "exact_dup_name_addr": dup})
    md_table(rows, f)

    f.write("### E5. Blocking channel split on true pairs: name-only vs address-only vs both-weak\n")
    HIGH, LOW = 80, 50  # token_set_ratio thresholds (0-100 scale); high = strong signal, low = weak
    name_hi = pos_stats["name_sim"] >= HIGH
    addr_hi = pos_stats["addr_sim"] >= HIGH
    both_weak = (pos_stats["name_sim"] < LOW) & (pos_stats["addr_sim"] < LOW)
    n_pairs = len(true_sample)
    rows = [{"pattern": "name-only (name>=80, addr<80)", "share": pct(int((name_hi & ~addr_hi).sum()), n_pairs)},
            {"pattern": "address-only (addr>=80, name<80)", "share": pct(int((addr_hi & ~name_hi).sum()), n_pairs)},
            {"pattern": "both strong (>=80/>=80)", "share": pct(int((name_hi & addr_hi).sum()), n_pairs)},
            {"pattern": f"both weak (<{LOW}/<{LOW})", "share": pct(int(both_weak.sum()), n_pairs)}]
    md_table(rows, f)

    f.write("### E6/E7. Naive blocking pool scale + blocked-negative vs random-negative hardness gap\n")
    # Cheap real blocking: top-20 candidates per S1 by name token_set_ratio, within-country, on a
    # sampled subset of S1 (full S1 x candidate brute force is too slow for an EDA script).
    BLOCK_K = 20
    s1_sample = rng.sample(list(s1_train), min(500, len(s1_train)))
    blocked_negs, blocked_pool_sizes = [], []
    for s1_id in s1_sample:
        n1, a1, c1 = s1_train[s1_id]
        pool = cand_ids_by_country.get(c1, [])
        if not pool:
            continue
        scored = sorted(((token_set_ratio(anyascii(n1).lower(), anyascii(train_lookup[cid][0]).lower()), cid)
                          for cid in rng.sample(pool, min(2000, len(pool)))), reverse=True)[:BLOCK_K]
        blocked_pool_sizes.append(len(scored))
        true_matches = truth.get(s1_id, frozenset())
        for _, cid in scored:
            if cid not in true_matches:
                blocked_negs.append((s1_id, cid))
    est_naive_pairs = BLOCK_K * len(s1_train)  # top-K per channel x |S1|, order-of-magnitude estimate
    f.write(f"- Estimated naive-blocking candidate count (top-{BLOCK_K} x |S1|={len(s1_train)}): ~{est_naive_pairs:,} "
            f"→ {'brute-force numpy cosine OK (<2M)' if est_naive_pairs < 2_000_000 else 'approaching/over 2M, consider FAISS'}\n")
    blocked_neg_sample = blocked_negs[:5000]
    if blocked_neg_sample:
        bstats = compute(blocked_neg_sample)
        rand_name_p50 = np.percentile(neg_stats["name_sim"], 50)
        block_name_p50 = np.percentile(bstats["name_sim"], 50)
        f.write(f"- Random-negative name_sim p50: {rand_name_p50:.1f} | Blocked-negative name_sim p50: {block_name_p50:.1f} "
                f"(gap: {block_name_p50 - rand_name_p50:+.1f}) — blocked negatives are the harder distribution "
                f"the matcher must be trained against (n={len(blocked_neg_sample)}).\n\n")

    f.write("## Decisions summary (fill in leaf confidence after reading the numbers above)\n")
    f.write("```\n")
    f.write("- Singleton rate: SEE A2/baseline_empty.py -> Leaf 4: <approach>\n")
    f.write("- Assignment violations: SEE A1 -> Hungarian matching: <justified | soft-constraint only>\n")
    f.write("- Region patterns found: SEE B5/D11/D12 -> Leaf 1 scope: <single ruleset | per-region>\n")
    f.write("- Blocking channel split: SEE E5 -> Leaf 2: <two-channel confirmed | rebalance k>\n")
    f.write("- Candidate pool at naive blocking: SEE E6 -> ANN: <brute-force ok | FAISS needed>\n")
    f.write("- Hard negative difficulty: SEE E7 -> <blocked vs random negative score gap>\n")
    f.write("```\n")

    f.close()
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
